### ISSUE TITLE
File import is failing with semicolon CSV

### ISSUE THREAD

**Issue by jeanmonod** [orocrm/crm#96]
Following #95, here is an issue dedicated to the semicolon CSV files

**Comment by akuzmenko-magecore** [comment]
Thank you. We have this improvement planned. We'll let you when it is available in release.
You can take a look at solutions suggested in a related issue https://github.com/orocrm/platform/issues/85. Maybe they will be helpful.

**Comment by jeanmonod** [comment]
Once you have understand that the file must be comma separated and not semicolon separated, it's quite easy to fix it. But we have lost some time to spot the issue. Maybe you should add a disclaimer to warm user that the file MUST be comma separated. It could save some frustration...

**Comment by artml** [comment]
Fixed in 1.7 version. Thanks for reporting this!

**Comment by sagikazarmark** [comment]
I would say this is not fixed, rather won't fix. Using comma instead of semicolons is no fix.

There are solutions: https://www.orocrm.com/forums/topic/import-csvfilereader

But I would say the available resources for this question are extremely low. The BatchBundle is super complicated and the above linked solution is the best I know so far. I would really like to see some cookbook entries about this topic.

**Comment by artml** [comment]
@sagikazarmark we are going to improve the CSV import functionality eventually, and I think will add support for semicolons and maybe other separators as well. But it's hard to say now when we are going to do it, other than "someday."

**Comment by sagikazarmark** [comment]
I sticked to this solution for now: https://github.com/webplates/platform-standard/commit/4253d990de64f1b1a2ba75ed3ef851903df25308
